### ISSUE TITLE
TAID0 map has improper coordinates for placing map characters

### ISSUE THREAD

**Issue by jonko0493** [haroohie-club/SerialLoops#101]
All of the other maps are correct and the pathing map in the map editor is correct, so this is a bit ??? for me.

Pathing map:
![image](https://user-images.githubusercontent.com/69772986/229616945-98f308b8-7fd5-4bc1-9571-392a3c8317d7.png)

The farthest Kyon can be dragged left/right:
![image](https://user-images.githubusercontent.com/69772986/229617226-1b564cd3-86d8-4fa1-ba35-8112f8c10ec4.png)

**Comment by WiIIiam278** [comment]
is the scale for the larger-sized maps not being applied here for the coordinate matrix, but it is for the graphics?

**Comment by jonko0493** [comment]
I'm not totally sure what's going wrong because it still does work for the other maps. 🤷 so it's a little confusing for sure.
