### ISSUE TITLE
Add full auto-updates

### ISSUE THREAD

**Issue by jonko0493** [haroohie-club/SerialLoops#130]
#127 added the auto-update checking and the scaffolding for downloading updates. Completing this issue means we're able to press a button and have the program download (and install?) itself.

**Comment by WiIIiam278** [comment]
after some discussion, I think we should make a sort of "data overmind loops" bootstrap/launcher applet to handle updates and also possibly dependency downloads

**Comment by jonko0493** [comment]
Closing in favor of https://github.com/haroohie-club/LoopyOvermind/issues/1
