### ISSUE TITLE
Documentation for v0.1

### ISSUE THREAD

**Issue by jonko0493** [haroohie-club/SerialLoops#135]
This should include:

* Updates to the wiki covering what each of the editors does
* Moving the script commands documentation to this repo
* Documentation for script templates (#102)
* Add tooltips explaining certain fields directly to the application itself

**Comment by WiIIiam278** [comment]
We should do a thing where we clone the wiki's markdown to the haroohie club site with some nice formatting so it can be easily indexed and look nice

**Comment by jonko0493** [comment]
Agreed. Are you thinking we do some sort of submodule thing?

**Comment by WiIIiam278** [comment]
Nah so, basically on our app's launch js script we clone the SerialLoops.wiki.git repo to a directory under /content (so /content/chokuretsu/serial-loops/docs), remove the .git folder and then render that with contentjs and nuxt. Pre-render to deploy on GH pages and it should work a treat. Hopefully

**Comment by WiIIiam278** [comment]
Idk if we want to add issue tracking to haroohie-site (we might if we want to do the community thing) but yeah one for there more then here

**Comment by jonko0493** [comment]
What would be the benefit of issue tracking on HaroohieSite over this repo? I think I'd prefer to keep the issues here, tbh -- seems nicer to have them all in one place (tho projects boards do work cross-repo).
