### ISSUE TITLE
"Sequence contains no elements" error when replacing a background with a grayscale image

### ISSUE THREAD

**Issue by WiIIiam278** [haroohie-club/SerialLoops#173]
This error appears whenever I attempt to replace a background with a new one with a lower resolution:

![image](https://user-images.githubusercontent.com/31187453/233714165-1be01f62-614a-4050-86ba-70aa0b4b4a1c.png)

We should probably show a more sensible error if you try and do this.

**Comment by jonko0493** [comment]
The issue here is with the color reduction algorithm, so I think I will just combine this with #111.
