### ISSUE TITLE
Add KBG export and replacement

### ISSUE THREAD

**Issue by jonko0493** [haroohie-club/SerialLoops#225]
Kinda forgot about these, but we should do them!

**Comment by WiIIiam278** [comment]
Don't these use some kind of vector format to support animating the layers, or am I misremembering something? (like iirc the "wave" effect on this works by sliding it along above the background).
Probably can export as a GIF quite easily, but importing may be a bit more complex

**Comment by jonko0493** [comment]
@WiIIiam278 I initially thought it was some sort of vector format but it's actually just directly inserting 4bpp tiles into sub screen VRAM. The "screen graphic" itself is just the layout of the tiles in VRAM. No real need to export as a GIF as it's a static background that's just scrolled along the screen by the sub engine itself.

**Comment by WiIIiam278** [comment]
Oh lol

**Comment by jonko0493** [comment]
This issue was opened without me realizing that I had done this, as far back as #4 for export (lmao). Import was added with all the rest of them in #119. However, it currently is not working well, so I'm gonna keep this open until I can fix it, I guess.

**Comment by jonko0493** [comment]
Ah wait, on closer inspection, it seems like we don't save screen data! So that's an oversight. Will fix.
