### ISSUE TITLE
Sound player should automatically reset after it's finished playing

### ISSUE THREAD

**Issue by WiIIiam278** [haroohie-club/SerialLoops#241]
Currently you have to manually press the STOP button before hitting play to re-play sound. It'd be nice (if possible) to have it automatically STOP when the sound has ended.

**Comment by jonko0493** [comment]
Alternatively, it would be nice if the main player could (optionally?) play the full looped audio

**Comment by jonko0493** [comment]
Implemented in Avalonia branch in BGM/voiced line sound player in #377 and in #401 for the SFX sound player.
