### ISSUE TITLE
Script editor doesn't correctly display the correct chibi used for OP_MODE

### ISSUE THREAD

**Issue by WiIIiam278** [haroohie-club/SerialLoops#257]
Only Kyon is able to be the chibi used for OP_MODE -- all other chibis are ignored.

![image](https://github.com/haroohie-club/SerialLoops/assets/31187453/bde2fee2-8d34-44d9-8cad-c28874c6b05a)

It's also worth mentioning that the game softlocks if no starting chibis are defined when using this command -- another one to add onto the validation list :)

**Comment by WiIIiam278** [comment]
> With the second part -- what do you mean? ![image](https://user-images.githubusercontent.com/69772986/247981202-a8d08652-97de-46e9-a709-3a6d7065233c.png)
> 
> This is base game -- no starting chibis define here. `OP_MODE` should bring Kyon out

Choose "Remove Starting Chibis" -- softlocks if that's disabled

**Comment by jonko0493** [comment]
ahhh gotcha, if the whole section has been deleted. that makes sense
