### ISSUE TITLE
DevkitARM is most likely out of date

### ISSUE THREAD

**Issue by myoaon01** [haroohie-club/SerialLoops#305]
![스크린샷 2023-11-14 130224](https://github.com/haroohie-club/SerialLoops/assets/123155901/8a16d137-23ac-4afc-8712-8525abe2535b)
![스크린샷 2023-11-14 130338](https://github.com/haroohie-club/SerialLoops/assets/123155901/7b715030-c3ae-4b03-9267-aac1d03bfa8c)
![스크린샷 2023-11-14 130737](https://github.com/haroohie-club/SerialLoops/assets/123155901/a46aaca5-226e-4e7f-a858-c8bada4a1163)
![스크린샷 2023-11-14 130906](https://github.com/haroohie-club/SerialLoops/assets/123155901/2c059afb-8020-4d1a-88f3-7802f5e64590)

I'm using Windows 11, and I downloaded updater from devkitpro github and installed the file.

**Comment by jonko0493** [comment]
Yep, correct, we're gonna need to update this! We got busy working on the release of episode 3 so haven't had a chance to touch this in a while. I think the correct solution is actually removing the dependency on a specific version of devkitARM entirely, which should be possible (will have to look into it a bit tho).

**Comment by jonko0493** [comment]
In any case, I'll start working on this shortly. Should get back into implementing features for v0.3 anyway!

**Comment by jonko0493** [comment]
Also, @myoaon01 -- in the meantime, as long as you're not assembling some of the pre-made ROM hacks, you should still be able to use the program despite the version mismatch!

**Comment by jonko0493** [comment]
Circling back on this. The solution here should be to remove the devkitARM specific version dependency. Will begin work on this shortly.

**Comment by jonko0493** [comment]
@myoaon01 I just pushed a PR to fix this; after we merge (hopefully tomorrow), the latest preview version of SL will no longer have this issue!
