### ISSUE TITLE
Refactor scripting UI logic

### ISSUE THREAD

**Issue by WiIIiam278** [haroohie-club/SerialLoops#313]
Scripting is fairly buggy at the moment and is in need of a refactor; specifically, decoupling the UI drag/drop/copy/paste logic from the actual validation and processing logic.

**Comment by jonko0493** [comment]
Putting this in the v0.3 milestone for now but I'd have no problem kicking it to v0.4 since it's a pretty big task.

Related existing bugs:
* #282
* #284 
* #285

**Comment by jonko0493** [comment]
I think we should keep this as part of v0.3 as we can work on it as part of #371.

**Comment by jonko0493** [comment]
This is in-progress and looking extremely good so far. Avalonia is making the script editor much more straightforward and so I think we'll be able to handle these changes more easily.
