### ISSUE TITLE
Tabs are loaded off screen when reloading project workspace

### ISSUE THREAD

**Issue by jonko0493** [haroohie-club/SerialLoops#85]
Works fine on Linux, but Mac and Windows definitely shouldn't have this. We had a similar bug before just with the tabs opening, but I don't remember exactly what fixed that. Do you, @WiIIiam278?

**Comment by WiIIiam278** [comment]
I don't recall sadly

I think this may be down to the parent bar control forcing all tabs to the left that aren't the currently open one.
